import React, { useCallback } from 'react';
import type { AnalysisResult } from '../types';
import type { UnitSystem } from '../App';
import { InfoIcon } from './icons';
import { Feedback } from './Feedback';

interface ResultDisplayProps {
    result: AnalysisResult;
    image: string | null;
    onReset: () => void;
    unitSystem: UnitSystem;
    onUnitChange: (system: UnitSystem) => void;
}

export const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, image, onReset, unitSystem, onUnitChange }) => {
    const { heightCm, weightKg, accuracy } = result;

    const totalInches = Math.round(heightCm / 2.54);
    const heightFeet = Math.floor(totalInches / 12);
    const heightInches = totalInches % 12;
    const weightLbs = (weightKg * 2.20462).toFixed(1);

    const hMain = unitSystem === 'imperial' ? `${heightFeet}'${heightInches}"` : `${heightCm.toFixed(0)} cm`;
    const hSub = unitSystem === 'imperial' ? `${heightCm.toFixed(0)} cm` : `${heightFeet}'${heightInches}"`;
    const wMain = unitSystem === 'imperial' ? `${weightLbs} lb` : `${weightKg.toFixed(1)} kg`;
    const wSub = unitSystem === 'imperial' ? `${weightKg.toFixed(1)} kg` : `${weightLbs} lb`;

    const generateShareCard = useCallback((): Promise<Blob | null> => {
        return new Promise((resolve) => {
            const canvas = document.createElement('canvas');
            canvas.width = 600;
            canvas.height = 400;
            const ctx = canvas.getContext('2d');
            if (!ctx) { resolve(null); return; }

            // Background
            ctx.fillStyle = '#0a0a0a';
            ctx.fillRect(0, 0, 600, 400);

            // Green accent bar
            ctx.fillStyle = '#00A562';
            ctx.fillRect(0, 0, 600, 4);

            // Logo text
            ctx.font = 'bold 28px "Space Grotesk", sans-serif';
            ctx.fillStyle = '#ffffff';
            ctx.fillText('Hei', 40, 55);
            ctx.fillStyle = '#00A562';
            ctx.fillText('wei.', 80, 55);

            // Divider
            ctx.fillStyle = '#262626';
            ctx.fillRect(40, 80, 520, 1);

            // Height
            ctx.fillStyle = '#00A562';
            ctx.font = 'bold 11px "Space Grotesk", sans-serif';
            ctx.fillText('HEIGHT', 40, 120);
            ctx.fillStyle = '#ffffff';
            ctx.font = 'bold 48px "Space Grotesk", sans-serif';
            ctx.fillText(hMain, 40, 175);
            ctx.fillStyle = '#737373';
            ctx.font = '16px "Space Grotesk", sans-serif';
            ctx.fillText(hSub, 40, 200);

            // Weight
            ctx.fillStyle = '#00A562';
            ctx.font = 'bold 11px "Space Grotesk", sans-serif';
            ctx.fillText('WEIGHT', 320, 120);
            ctx.fillStyle = '#ffffff';
            ctx.font = 'bold 48px "Space Grotesk", sans-serif';
            ctx.fillText(wMain, 320, 175);
            ctx.fillStyle = '#737373';
            ctx.font = '16px "Space Grotesk", sans-serif';
            ctx.fillText(wSub, 320, 200);

            // Confidence badge
            const badgeColors: Record<string, string> = { high: '#22c55e', medium: '#eab308', low: '#f97316' };
            ctx.fillStyle = badgeColors[accuracy] || '#22c55e';
            ctx.beginPath();
            ctx.arc(52, 250, 5, 0, Math.PI * 2);
            ctx.fill();
            ctx.fillStyle = '#a1a1aa';
            ctx.font = 'bold 12px "Space Grotesk", sans-serif';
            ctx.fillText(`${accuracy.toUpperCase()} CONFIDENCE`, 66, 254);

            // Divider
            ctx.fillStyle = '#262626';
            ctx.fillRect(40, 290, 520, 1);

            // Watermark
            ctx.fillStyle = '#525252';
            ctx.font = '12px "Space Grotesk", sans-serif';
            ctx.fillText('hei-wei.vercel.app  •  Powered by Spatial AI', 40, 340);

            // Disclaimer
            ctx.fillStyle = '#404040';
            ctx.font = '10px "Space Grotesk", sans-serif';
            ctx.fillText('Estimates generated by AI. Not medical data.', 40, 370);

            canvas.toBlob((blob) => resolve(blob), 'image/png');
        });
    }, [hMain, hSub, wMain, wSub, accuracy]);

    const handleDownload = useCallback(async () => {
        const blob = await generateShareCard();
        if (!blob) return;
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'heiwei-results.png';
        a.click();
        URL.revokeObjectURL(url);
    }, [generateShareCard]);

    const handleShare = useCallback(async () => {
        const blob = await generateShareCard();
        if (!blob) return;
        const file = new File([blob], 'heiwei-results.png', { type: 'image/png' });
        if (navigator.share && navigator.canShare?.({ files: [file] })) {
            try {
                await navigator.share({ files: [file], title: 'My Hei-wei Results', text: `Height: ${hMain} | Weight: ${wMain}` });
            } catch { }
        } else {
            handleDownload();
        }
    }, [generateShareCard, hMain, wMain, handleDownload]);

    return (
        <div className="animate-fade-in-up w-full h-full flex flex-col lg:flex-row gap-8 lg:gap-14">

            {/* Left Col: Image */}
            <div className="w-full lg:w-5/12 flex-shrink-0">
                <div className="relative w-full min-h-[50vh] lg:min-h-[60vh] bg-black rounded-2xl overflow-hidden border border-neutral-800 shadow-2xl sticky top-8 mx-auto max-w-md lg:max-w-none">
                    {image && (
                        <img src={`data:image/jpeg;base64,${image}`} alt="Analyzed Subject" className="w-full h-full object-contain absolute inset-0" />
                    )}
                    <div className="absolute bottom-0 inset-x-0 p-6 bg-gradient-to-t from-black/80 to-transparent">
                        <span className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-bold uppercase tracking-widest border backdrop-blur-md ${accuracy === 'high' ? 'bg-green-500/20 text-green-300 border-green-500/20' :
                            accuracy === 'medium' ? 'bg-yellow-500/20 text-yellow-300 border-yellow-500/20' :
                                'bg-orange-500/20 text-orange-300 border-orange-500/20'
                            }`}>
                            <span className={`w-1.5 h-1.5 rounded-full ${accuracy === 'high' ? 'bg-green-400' :
                                accuracy === 'medium' ? 'bg-yellow-400' : 'bg-orange-400'
                                }`}></span>
                            {accuracy} Confidence
                        </span>
                    </div>
                </div>
            </div>

            {/* Right Col: Stats & Controls */}
            <div className="w-full lg:w-7/12 flex flex-col justify-center">
                <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-8 lg:mb-10 gap-5">
                    <h2 className="text-4xl lg:text-5xl font-black text-white tracking-tight">Analysis Results</h2>
                    <div className="flex bg-neutral-900 p-1 rounded-xl border border-neutral-800">
                        <button
                            onClick={() => onUnitChange('metric')}
                            className={`px-5 py-2 rounded-lg text-sm font-bold tracking-widest uppercase transition-all ${unitSystem === 'metric' ? 'bg-brand text-white' : 'text-zinc-500 hover:text-zinc-300'}`}
                        >
                            Metric
                        </button>
                        <button
                            onClick={() => onUnitChange('imperial')}
                            className={`px-5 py-2 rounded-lg text-base font-bold tracking-widest uppercase transition-all ${unitSystem === 'imperial' ? 'bg-brand text-white' : 'text-zinc-500 hover:text-zinc-300'}`}
                        >
                            Imperial
                        </button>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-5 lg:gap-6 mb-8 lg:mb-10">
                    {/* Height Card */}
                    <div className="bg-neutral-900 rounded-2xl p-8 lg:p-9 border border-neutral-800 relative overflow-hidden group hover:border-brand/30 transition-colors">
                        <div className="absolute top-0 right-0 p-6 opacity-[0.06] group-hover:opacity-10 transition-opacity">
                            <span className="text-8xl font-black text-white">H</span>
                        </div>
                        <p className="text-base font-bold text-brand uppercase tracking-[0.3em] mb-4">Height</p>
                        <p className="text-6xl lg:text-7xl leading-none font-black text-white tracking-tight mb-3">{hMain}</p>
                        <p className="text-lg font-medium text-zinc-500">{hSub}</p>
                    </div>

                    {/* Weight Card */}
                    <div className="bg-neutral-900 rounded-2xl p-8 lg:p-9 border border-neutral-800 relative overflow-hidden group hover:border-brand/30 transition-colors">
                        <div className="absolute top-0 right-0 p-6 opacity-[0.06] group-hover:opacity-10 transition-opacity">
                            <span className="text-8xl font-black text-white">W</span>
                        </div>
                        <p className="text-base font-bold text-brand uppercase tracking-[0.3em] mb-4">Weight</p>
                        <p className="text-6xl lg:text-7xl leading-none font-black text-white tracking-tight mb-3">{wMain}</p>
                        <p className="text-lg font-medium text-zinc-500">{wSub}</p>
                    </div>
                </div>

                <div className="flex flex-col gap-4">
                    <div className="p-4 bg-neutral-900 border border-neutral-800 rounded-xl flex items-center gap-4">
                        <InfoIcon className="w-5 h-5 text-zinc-500 ml-1 flex-shrink-0" />
                        <p className="text-base text-zinc-500 leading-relaxed">
                            These estimates are generated by AI based on visual markers and should not be considered medical data. Lighting, clothing, and camera angle affect precision.
                        </p>
                    </div>

                    {/* Action Buttons */}
                    <div className="flex flex-col sm:flex-row gap-3 mt-4">
                        <button
                            onClick={onReset}
                            className="flex-1 group bg-brand hover:bg-brand-light text-white px-6 py-4 rounded-xl font-bold flex items-center justify-center gap-3 transition-all active:scale-95"
                        >
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                            </svg>
                            New Analysis
                        </button>
                        <button
                            onClick={handleShare}
                            className="flex-1 group bg-neutral-900 hover:bg-neutral-800 text-zinc-300 px-6 py-4 rounded-xl font-bold flex items-center justify-center gap-3 transition-all border border-neutral-700 active:scale-95"
                        >
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M7.217 10.907a2.25 2.25 0 100 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186l9.566-5.314m-9.566 7.5l9.566 5.314m0 0a2.25 2.25 0 103.935 2.186 2.25 2.25 0 00-3.935-2.186zm0-12.814a2.25 2.25 0 103.933-2.185 2.25 2.25 0 00-3.933 2.185z" />
                            </svg>
                            Share
                        </button>
                        <button
                            onClick={handleDownload}
                            className="flex-1 group bg-neutral-900 hover:bg-neutral-800 text-zinc-300 px-6 py-4 rounded-xl font-bold flex items-center justify-center gap-3 transition-all border border-neutral-700 active:scale-95"
                        >
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                            </svg>
                            Save
                        </button>
                    </div>
                </div>
                <Feedback />
            </div>
        </div>
    );
};